; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32@^6.10.0
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino

# For main PC
#upload_port = COM7
# For laptop
upload_port = COM8

upload_speed = 921600

# For main PC
#monitor_port = COM8
# For laptop
monitor_port = COM9

monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    0xcafedecaf/VanBus @ ^0.4.1